---
- name: Delete a Virtual Private (VPC) Cloud at GCP
  hosts: localhost
  connection: local

  tasks:

    - name: Ensure the vpc is gone
      register: network
      google.cloud.gcp_compute_network:
        name: "{{ net_instance }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: "{{ state }}"

    - name: Print shit out
      ansible.builtin.debug:
        var: network
...
